# Generated by Django 3.2.20 on 2023-10-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
